/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CodeimpostorIndexRouteImport } from './routes/codeimpostor/index'
import { Route as CodeimpostorHostRouteImport } from './routes/codeimpostor/host'
import { Route as CodeimpostorUnirseRouteImport } from './routes/codeimpostor/unirse'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeimpostorIndexRoute = CodeimpostorIndexRouteImport.update({
  id: '/codeimpostor/',
  path: '/codeimpostor/',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeimpostorHostRoute = CodeimpostorHostRouteImport.update({
  id: '/codeimpostor/host',
  path: '/codeimpostor/host',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeimpostorUnirseRoute = CodeimpostorUnirseRouteImport.update({
  id: '/codeimpostor/unirse',
  path: '/codeimpostor/unirse',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/codeimpostor/host': typeof CodeimpostorHostRoute
  '/codeimpostor/unirse': typeof CodeimpostorUnirseRoute
  '/codeimpostor/': typeof CodeimpostorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/codeimpostor/host': typeof CodeimpostorHostRoute
  '/codeimpostor/unirse': typeof CodeimpostorUnirseRoute
  '/codeimpostor': typeof CodeimpostorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/codeimpostor/host': typeof CodeimpostorHostRoute
  '/codeimpostor/unirse': typeof CodeimpostorUnirseRoute
  '/codeimpostor/': typeof CodeimpostorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/codeimpostor/host' | '/codeimpostor/unirse' | '/codeimpostor/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/codeimpostor/host' | '/codeimpostor/unirse' | '/codeimpostor'
  id:
    | '__root__'
    | '/'
    | '/codeimpostor/host'
    | '/codeimpostor/unirse'
    | '/codeimpostor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CodeimpostorHostRoute: typeof CodeimpostorHostRoute
  CodeimpostorUnirseRoute: typeof CodeimpostorUnirseRoute
  CodeimpostorIndexRoute: typeof CodeimpostorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codeimpostor/': {
      id: '/codeimpostor/'
      path: '/codeimpostor'
      fullPath: '/codeimpostor/'
      preLoaderRoute: typeof CodeimpostorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codeimpostor/host': {
      id: '/codeimpostor/host'
      path: '/codeimpostor/host'
      fullPath: '/codeimpostor/host'
      preLoaderRoute: typeof CodeimpostorHostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codeimpostor/unirse': {
      id: '/codeimpostor/unirse'
      path: '/codeimpostor/unirse'
      fullPath: '/codeimpostor/unirse'
      preLoaderRoute: typeof CodeimpostorUnirseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CodeimpostorHostRoute: CodeimpostorHostRoute,
  CodeimpostorUnirseRoute: CodeimpostorUnirseRoute,
  CodeimpostorIndexRoute: CodeimpostorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
